[package]
name = "codegen-lib"
version = "0.1.0"
authors = ["Tianjiao Huang <git@tjhu.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
