[package]
name = "ridl"
version = "0.1.0"
authors = ["David Detweiler <detweild@uci.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "", features = ["full"] }
quote = { version = "" }
